### ISSUE TITLE
saasherder get-images.sh script returns duplicate container entries

### ISSUE THREAD

**Issue by navidshaikh** [navidshaikh/scanning#17]
get-images.sh script is aimed to figure out osio prod containers. The script exports the containers in a local file `images.txt`.
We observed there are duplicate container entries are listed in `images.txt` file. 
The current run of script lists

- `bayesian/cucos-worker:3e58820` container - 8 times
- `bayesian/kronos:c21f911` container - 2 times

**Comment by navidshaikh** [comment]
@jmelis @bamachrn FYI

**Comment by jmelis** [comment]
This is expected, several containers use the same image.

**Comment by navidshaikh** [comment]
@jmelis : oh! okay. Thanks for the input. We will `set` before queuing containers for scanning.
